## Setup

In [1]:
from blaze import Data, discover, compute, symbol

In [2]:
DATA_DIR = '/Users/Will/Data/blaze_data/'

In [13]:
db = Data('sqlite:////' + DATA_DIR + 'lahman2013.sqlite')

In [16]:
df = db.Batting

## How it Should work 

In [17]:
df

playerID  yearID  stint teamID lgID    G  G_batting   AB    R    H  \
0   aardsda01    2004      1    SFN   NL   11         11    0    0    0   
1   aardsda01    2006      1    CHN   NL   45         43    2    0    0   
2   aardsda01    2007      1    CHA   AL   25          2    0    0    0   
3   aardsda01    2008      1    BOS   AL   47          5    1    0    0   
4   aardsda01    2009      1    SEA   AL   73          3    0    0    0   
5   aardsda01    2010      1    SEA   AL   53          4    0    0    0   
6   aardsda01    2012      1    NYA   AL    1        NaN  NaN  NaN  NaN   
7   aardsda01    2013      1    NYN   NL   43         43    0    0    0   
8   aaronha01    1954      1    ML1   NL  122        122  468   58  131   
9   aaronha01    1955      1    ML1   NL  153        153  602  105  189   
10  aaronha01    1956      1    ML1   NL  153        153  609  106  200   

    ...    SB  CS  BB  SO  IBB  HBP  SH  SF  GIDP  G_old  
0   ...     0   0   0   0    0    0   0   0     0     11  
1   ...     0   0   0   0    0    0   1   0     0     45  
2   ...     0   0   0   0    0    0   0   0     0      2  
3   ...     0   0   0   1    0    0   0   0     0      5  
4   ...     0   0   0   0    0    0   0   0     0    NaN  
5   ...     0   0   0   0    0    0   0   0     0    NaN  
6   ...   NaN NaN NaN NaN  NaN  NaN NaN NaN   NaN    NaN  
7   ...     0   0   0   0    0    0   0   0     0    NaN  
8   ...     2   2  28  39  NaN    3   6   4    13    122  
9   ...     3   1  49  61    5    3   7   4    20    153  
10  ...     2   4  37  54    6    2   5   7    21    153  

...

In [5]:
type(df)

blaze.expr.expressions.Field

In [6]:
df.playerID[5:10]

Data:       Engine(sqlite://///Users/Will/Data/blaze_data/lahman2013.sqlite)
Expr:       _1.Batting.playerID[5:10]
DataShape:  5 * ?string

In [7]:
df[:2]

Data:       Engine(sqlite://///Users/Will/Data/blaze_data/lahman2013.sqlite)
Expr:       _1.Batting[:2]
DataShape:  2 * {
  playerID: ?string,
  yearID: ?int32,
  stint: ?int32,
  teamID: ?string,
  lgID: ?string,
  G: ?int32,
  ...

In [49]:
df.head()

playerID  yearID  stint teamID lgID    G  G_batting   AB    R    H  ...    \
0  aardsda01    2004      1    SFN   NL   11         11    0    0    0  ...     
1  aardsda01    2006      1    CHN   NL   45         43    2    0    0  ...     
2  aardsda01    2007      1    CHA   AL   25          2    0    0    0  ...     
3  aardsda01    2008      1    BOS   AL   47          5    1    0    0  ...     
4  aardsda01    2009      1    SEA   AL   73          3    0    0    0  ...     
5  aardsda01    2010      1    SEA   AL   53          4    0    0    0  ...     
6  aardsda01    2012      1    NYA   AL    1        NaN  NaN  NaN  NaN  ...     
7  aardsda01    2013      1    NYN   NL   43         43    0    0    0  ...     
8  aaronha01    1954      1    ML1   NL  122        122  468   58  131  ...     
9  aaronha01    1955      1    ML1   NL  153        153  602  105  189  ...     

   SB  CS  BB  SO  IBB  HBP  SH  SF  GIDP  G_old  
0   0   0   0   0    0    0   0   0     0     11  
1   0   0   0   0    0    0   1   0     0     45  
2   0   0   0   0    0    0   0   0     0      2  
3   0   0   0   1    0    0   0   0     0      5  
4   0   0   0   0    0    0   0   0     0    NaN  
5   0   0   0   0    0    0   0   0     0    NaN  
6 NaN NaN NaN NaN  NaN  NaN NaN NaN   NaN    NaN  
7   0   0   0   0    0    0   0   0     0    NaN  
8   2   2  28  39  NaN    3   6   4    13    122  
9   3   1  49  61    5    3   7   4    20    153  

[10 rows x 24 columns]

## How the test works

In [8]:
import pandas as pd
test_df = pd.DataFrame([['Alice', 100, 1],
                ['Bob', 200, 2],
                ['Alice', 50, 3]], columns=['name', 'amount', 'id'])

t = symbol('t', discover(test_df))

In [9]:
compute(t[0:2], test_df)

name  amount  id
0  Alice     100   1
1    Bob     200   2

In [10]:
import pandas as pd
test_df = Data(test_df)

t = symbol('t', discover(test_df))

In [11]:
compute(t[0:2], test_df) # Not Implemented Error

NotImplementedError: Don't know how to compute:
expr: t[0:2]
data: {t:     name  amount  id
0  Alice     100   1
1    Bob     200   2
2  Alice      50   3}

In [62]:
df.H.distinct().head(5)

H
0    0
1  NaN
2  131
3  189
4  200

In [63]:
from numpy import random

In [67]:
items = []
for item in df.H.distinct():
    items.append(item)
    if len(items) == 50:
        break
random.choice(items, 20)

array([131, 131, 62, 184, 10, 198, 198, 12, 200, 91, 5, 170, 6, 198, 12,
       78, 189, 191, 170, 10], dtype=object)

## Fun with SQL Alchemy

In [18]:
import sqlalchemy

In [29]:
engine = sqlalchemy.create_engine('sqlite:////' + DATA_DIR + 'lahman2013.sqlite')

In [30]:
connection = engine.connect()

In [33]:
from sqlalchemy.orm import sessionmaker

In [34]:
session = sessionmaker(bind=engine)

In [36]:
session = session()

In [38]:
session.query(Batting.yearID)

NameError: name 'Batting' is not defined

# How slicing in handled in SQl ALchemy 

[Stack Overflow.](http://stackoverflow.com/questions/12111925/how-can-i-limit-the-number-of-returned-results-to-only-the-1000-latest-entries-w)

`limitedQuery = q[:50]`

[Slice](http://docs.sqlalchemy.org/en/improve_toc/orm/query.html) can be seen here.

# How Blaze Slicing works

In [69]:
import numpy as np

In [71]:
array = np.array(range(2,24))

In [73]:
len(array[:5])

5

In [75]:
d_array = Data(array)

In [77]:
len(d_array[:5])

5

# Design Choices

1. Test directly with computation
2. Use the compute function to work. 

Try (2) first because it is more traditional. It might be worth looking at this in the future to see how that works.

# Sql compute test

In [82]:

metadata = sa.MetaData()

s = sa.Table('accounts', metadata,
             sa.Column('name', sa.String),
             sa.Column('amount', sa.Integer),
             sa.Column('id', sa.Integer, primary_key=True))

In [83]:
s

Table('accounts', MetaData(bind=None), Column('name', String(), table=<accounts>), Column('amount', Integer(), table=<accounts>), Column('id', Integer(), table=<accounts>, primary_key=True, nullable=False), schema=None)

In [88]:
from blaze.compute.sql import (compute, computefull, select, lower_column,
                               compute_up)
import re
def normalize(s):
    s = ' '.join(s.strip().split()).lower()
    s = re.sub(r'(alias)_?\d*', r'\1', s)
    return re.sub(r'__([A-Za-z_][A-Za-z_0-9]*)', r'\1', s)

def test_table():
    result = str(computefull(t, s))
    expected = """
    SELECT accounts.name, accounts.amount, accounts.id
    FROM accounts
    """.strip()

    assert normalize(result) == normalize(expected)
    print(result)
test_table()

SELECT accounts.name, accounts.amount, accounts.id 
FROM accounts


In [90]:
def test_selection():
    assert str(compute(t[t['amount'] == 0], s)) == \
        str(sa.select([s]).where(s.c.amount == 0))
    assert str(compute(t[t['amount'] > 150], s)) == \
        str(sa.select([s]).where(s.c.amount > 150))
    
test_selection()

In [95]:
print(compute(t[t['amount'] == 0], s))

SELECT accounts.name, accounts.amount, accounts.id 
FROM accounts 
WHERE accounts.amount = :amount_1


In [93]:
print(sa.select([s]).where(s.c.amount == 0))

SELECT accounts.name, accounts.amount, accounts.id 
FROM accounts 
WHERE accounts.amount = :amount_1


In [81]:
s = sa.Table('accounts', metadata,
             sa.Column('name', sa.String),
             sa.Column('amount', sa.Integer),
             sa.Column('id', sa.Integer, primary_key=True))

NameError: name 'metadata' is not defined

In [195]:
import sqlalchemy as sa
def data():
    # make the engine
    engine = sa.create_engine('sqlite:///:memory:')
    metadata = sa.MetaData(engine)

    # name table
    name = sa.Table('name', metadata,
                    sa.Column('id', sa.Integer),
                    sa.Column('name', sa.String),
                    )
    name.create()

    # city table
    city = sa.Table('city', metadata,
                    sa.Column('id', sa.Integer),
                    sa.Column('city', sa.String),
                    sa.Column('country', sa.String),
                    )
    city.create()

    s = symbol('s', discover(engine))
    return {'engine': engine, 'metadata': metadata, 'name': name, 'city': city,
            's': s}

In [196]:
data = data()

In [103]:
type(data)

dict

In [110]:
type(data['s'])

blaze.expr.expressions.Symbol

## Making the SQL Dataset

Comes from line 1034 of test SQL

In [190]:
from blaze import join, by, into


engine = sa.create_engine('sqlite:///:memory:')

df_aaa = pd.DataFrame({'x': [1, 2, 3, 2, 3],
                    'y': [2, 1, 2, 3, 1],
                    'z': [3, 3, 3, 1, 2]})
df_bbb = pd.DataFrame({'w': [1, 2, 3, 2, 3],
                    'x': [2, 1, 2, 3, 1],
                    'y': [3, 3, 3, 1, 2]})

df_aaa.to_sql('aaa', engine)
df_bbb.to_sql('bbb', engine)

metadata = sa.MetaData(engine)
metadata.reflect()

sql_aaa = metadata.tables['aaa']
sql_bbb = metadata.tables['bbb']

L = symbol('aaa', discover(df_aaa))
R = symbol('bbb', discover(df_bbb))

expr = join(by(L.x, y_total=L.y.sum()),
                R)

a = compute(expr, {L: df_aaa, R: df_bbb})

b = compute(expr, {L: sql_aaa, R: sql_bbb})

x  y_total  w  y
0  1        2  2  3
1  1        2  3  2
2  2        4  1  3
3  2        4  3  3
4  3        3  2  1

In [123]:
sql_aaa

Table('aaa', MetaData(bind=Engine(sqlite:///:memory:)), Column('index', BIGINT(), table=<aaa>), Column('x', BIGINT(), table=<aaa>), Column('y', BIGINT(), table=<aaa>), Column('z', BIGINT(), table=<aaa>), schema=None)

In [121]:
metadata

MetaData(bind=Engine(sqlite:///:memory:))

In [138]:

a

x  y_total  w  y
0  1        2  2  3
1  1        2  3  2
2  2        4  1  3
3  2        4  3  3
4  3        3  2  1

In [143]:
a

x  y_total  w  y
0  1        2  2  3
1  1        2  3  2
2  2        4  1  3
3  2        4  3  3
4  3        3  2  1

In [146]:
into(list, a) == into(list, b)

False

In [176]:
into(list, a)

[(1, 2, 2, 3), (1, 2, 3, 2), (2, 4, 1, 3), (2, 4, 3, 3), (3, 3, 2, 1)]

In [180]:
into(list, b).contains(i for i in into(list, a))

AttributeError: 'list' object has no attribute 'contains'

In [159]:
a = into(list, b)

In [165]:
into(pd.DataFrame, b)

0  1  2  3
0  2  4  1  3
1  1  2  2  3
2  2  4  3  3
3  3  3  2  1
4  1  2  3  2

In [166]:
into(pd.DataFrame, a) 

0  1  2  3
0  1  2  2  3
1  1  2  3  2
2  2  4  1  3
3  2  4  3  3
4  3  3  2  1

In [169]:
into(pd.DataFrame, b)

0  1  2  3
0  2  4  1  3
1  1  2  2  3
2  2  4  3  3
3  3  3  2  1
4  1  2  3  2

### Now for the testing, we have that

In [185]:
into(pd.DataFrame,a)

0  1  2  3
0  1  2  2  3
1  1  2  3  2
2  2  4  1  3
3  2  4  3  3
4  3  3  2  1

In [187]:
for row in into(pd.DataFrame,b):
    print(row)

0
1
2
3


In [189]:
len(into(pd.DataFrame,b)) == len(into(pd.DataFrame, a))

True

In [186]:
into(pd.DataFrame,b).isin(i for i in into(pd.DataFrame,a))

0      1     2     3
0  True  False  True  True
1  True   True  True  True
2  True  False  True  True
3  True   True  True  True
4  True   True  True  True

# How we will test  

Numpy Test slicing works like this:

In [201]:
ax = np.arange(30, dtype='f4').reshape((5, 3, 2))

a = symbol('a', discover(ax))


inds = [0, slice(2), slice(1, 3), slice(None, None, 2), [1, 2, 3],
        (0, 1), (0, slice(1, 3)), (slice(0, 3), slice(3, 1, -1)),
        (0, [1, 2])]
for s in inds:
    print(compute(a[s], ax))


[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]]
[[[  0.   1.]
  [  2.   3.]
  [  4.   5.]]

 [[  6.   7.]
  [  8.   9.]
  [ 10.  11.]]]
[[[  6.   7.]
  [  8.   9.]
  [ 10.  11.]]

 [[ 12.  13.]
  [ 14.  15.]
  [ 16.  17.]]]
[[[  0.   1.]
  [  2.   3.]
  [  4.   5.]]

 [[ 12.  13.]
  [ 14.  15.]
  [ 16.  17.]]

 [[ 24.  25.]
  [ 26.  27.]
  [ 28.  29.]]]
[[[  6.   7.]
  [  8.   9.]
  [ 10.  11.]]

 [[ 12.  13.]
  [ 14.  15.]
  [ 16.  17.]]

 [[ 18.  19.]
  [ 20.  21.]
  [ 22.  23.]]]
[ 2.  3.]
[[ 2.  3.]
 [ 4.  5.]]
[[[  4.   5.]]

 [[ 10.  11.]]

 [[ 16.  17.]]]
[[ 2.  3.]
 [ 4.  5.]]


In [202]:
a[:5]

a[:5]

# Modifying the test 

In [232]:
def test_join_on_same_table():
    metadata = sa.MetaData()
    T = sa.Table('tab', metadata,
                 sa.Column('a', sa.Integer),
                 sa.Column('b', sa.Integer),
                 )

    t = symbol('tab', discover(T))
    expr = join(t, t, 'a')

    result = compute(expr, {t: T})

    assert normalize(str(result)) == normalize("""
    SELECT tab_left.a, tab_left.b, tab_right.b
    FROM tab AS tab_left JOIN tab AS tab_right
    ON tab_left.a = tab_right.a
    """)

In [233]:
test_join_on_same_table()

In [237]:
metadata = sa.MetaData()
T = sa.Table('tab', metadata,
                 sa.Column('a', sa.Integer),
                 sa.Column('b', sa.Integer),
                 )

In [238]:
t = symbol('tab', discover(T))

In [239]:
expr = join(t, t, 'a')

In [244]:
print(compute(expr, {t: T}))

SELECT tab_left.a, tab_left.b, tab_right.b 
FROM tab AS tab_left JOIN tab AS tab_right ON tab_left.a = tab_right.a


In [248]:
s = sa.Table('accounts', metadata,
             sa.Column('name', sa.String),
             sa.Column('amount', sa.Integer),
             sa.Column('id', sa.Integer, primary_key=True))

In [254]:
limit = 50
offset = 50
expected = normalize("""
SELECT * FROM accounts LIMIT {0} OFFSET {1}
""").format(limit, offset)

In [255]:
expected

'select * from accounts limit 50 offset 50'

In [ ]:
def test_distinct_multiple_columns():
    assert normalize(str(compute(t.distinct(), s))) == normalize("""
    SELECT DISTINCT accounts.name, accounts.amount, accounts.id
    FROM accounts""")

## Head Test

This one is the closest to what I am trying to do. Note that :param1 can just be anything.