## Setup

In [20]:
from blaze import Data, compute
DATA_DIR = '/Users/Will/Data/blaze_data/'
db = Data('sqlite:////' + DATA_DIR + 'lahman2013.sqlite')
# df = db.Batting # This is a field
# df = Data(db.Batting) # This is an interactive symbol

## How it Should work 

In [3]:
type(df)

blaze.interactive.InteractiveSymbol

In [24]:
type(db.Batting.head())

blaze.expr.collections.Head

In [25]:
type(db.Batting[3:4])

blaze.expr.expressions.Slice

In [21]:
str(db.Batting[2:10])

'_3.Batting[2:10]'

In [22]:
str(compute(db.Batting[40:60]))

NotImplementedError: Don't know how to compute:
expr: Batting[40:60]
data: {Batting: Table('Batting', MetaData(bind=Engine(sqlite://///Users/Will/Data/blaze_data/lahman2013.sqlite)), Column('playerID', TEXT(), table=<Batting>), Column('yearID', INTEGER(), table=<Batting>), Column('stint', INTEGER(), table=<Batting>), Column('teamID', TEXT(), table=<Batting>), Column('lgID', TEXT(), table=<Batting>), Column('G', INTEGER(), table=<Batting>), Column('G_batting', INTEGER(), table=<Batting>), Column('AB', INTEGER(), table=<Batting>), Column('R', INTEGER(), table=<Batting>), Column('H', INTEGER(), table=<Batting>), Column('2B', INTEGER(), table=<Batting>), Column('3B', INTEGER(), table=<Batting>), Column('HR', INTEGER(), table=<Batting>), Column('RBI', INTEGER(), table=<Batting>), Column('SB', INTEGER(), table=<Batting>), Column('CS', INTEGER(), table=<Batting>), Column('BB', INTEGER(), table=<Batting>), Column('SO', INTEGER(), table=<Batting>), Column('IBB', INTEGER(), table=<Batting>), Column('HBP', INTEGER(), table=<Batting>), Column('SH', INTEGER(), table=<Batting>), Column('SF', INTEGER(), table=<Batting>), Column('GIDP', INTEGER(), table=<Batting>), Column('G_old', INTEGER(), table=<Batting>), schema=None)}

In [13]:
db.Batting.head()

playerID  yearID  stint teamID lgID    G  G_batting   AB    R    H  ...    \
0  aardsda01    2004      1    SFN   NL   11         11    0    0    0  ...     
1  aardsda01    2006      1    CHN   NL   45         43    2    0    0  ...     
2  aardsda01    2007      1    CHA   AL   25          2    0    0    0  ...     
3  aardsda01    2008      1    BOS   AL   47          5    1    0    0  ...     
4  aardsda01    2009      1    SEA   AL   73          3    0    0    0  ...     
5  aardsda01    2010      1    SEA   AL   53          4    0    0    0  ...     
6  aardsda01    2012      1    NYA   AL    1        NaN  NaN  NaN  NaN  ...     
7  aardsda01    2013      1    NYN   NL   43         43    0    0    0  ...     
8  aaronha01    1954      1    ML1   NL  122        122  468   58  131  ...     
9  aaronha01    1955      1    ML1   NL  153        153  602  105  189  ...     

   SB  CS  BB  SO  IBB  HBP  SH  SF  GIDP  G_old  
0   0   0   0   0    0    0   0   0     0     11  
1   0   0   0   0    0    0   1   0     0     45  
2   0   0   0   0    0    0   0   0     0      2  
3   0   0   0   1    0    0   0   0     0      5  
4   0   0   0   0    0    0   0   0     0    NaN  
5   0   0   0   0    0    0   0   0     0    NaN  
6 NaN NaN NaN NaN  NaN  NaN NaN NaN   NaN    NaN  
7   0   0   0   0    0    0   0   0     0    NaN  
8   2   2  28  39  NaN    3   6   4    13    122  
9   3   1  49  61    5    3   7   4    20    153  

[10 rows x 24 columns]

In [17]:
str(db.Batting.head())

'_1.Batting.head(10)'

In [5]:
type(df)

blaze.expr.expressions.Field

In [6]:
df.playerID[5:10]

Data:       Engine(sqlite://///Users/Will/Data/blaze_data/lahman2013.sqlite)
Expr:       _1.Batting.playerID[5:10]
DataShape:  5 * ?string

In [7]:
df[:2]

Data:       Engine(sqlite://///Users/Will/Data/blaze_data/lahman2013.sqlite)
Expr:       _1.Batting[:2]
DataShape:  2 * {
  playerID: ?string,
  yearID: ?int32,
  stint: ?int32,
  teamID: ?string,
  lgID: ?string,
  G: ?int32,
  ...

In [321]:
df.head()

Data:       _4.Batting
Expr:       _5.head(10)
DataShape:  10 * {
  playerID: ?string,
  yearID: ?int32,
  stint: ?int32,
  teamID: ?string,
  lgID: ?string,
  G: ?int32,
  ...

## How the test works

In [8]:
import pandas as pd
test_df = pd.DataFrame([['Alice', 100, 1],
                ['Bob', 200, 2],
                ['Alice', 50, 3]], columns=['name', 'amount', 'id'])

t = symbol('t', discover(test_df))

In [9]:
compute(t[0:2], test_df)

name  amount  id
0  Alice     100   1
1    Bob     200   2

In [10]:
import pandas as pd
test_df = Data(test_df)

t = symbol('t', discover(test_df))

In [11]:
compute(t[0:2], test_df) # Not Implemented Error

NotImplementedError: Don't know how to compute:
expr: t[0:2]
data: {t:     name  amount  id
0  Alice     100   1
1    Bob     200   2
2  Alice      50   3}

In [62]:
df.H.distinct().head(5)

H
0    0
1  NaN
2  131
3  189
4  200

In [63]:
from numpy import random

In [67]:
items = []
for item in df.H.distinct():
    items.append(item)
    if len(items) == 50:
        break
random.choice(items, 20)

array([131, 131, 62, 184, 10, 198, 198, 12, 200, 91, 5, 170, 6, 198, 12,
       78, 189, 191, 170, 10], dtype=object)

## Fun with SQL Alchemy

In [18]:
import sqlalchemy

In [29]:
engine = sqlalchemy.create_engine('sqlite:////' + DATA_DIR + 'lahman2013.sqlite')

In [30]:
connection = engine.connect()

In [33]:
from sqlalchemy.orm import sessionmaker

In [34]:
session = sessionmaker(bind=engine)

In [36]:
session = session()

In [38]:
session.query(Batting.yearID)

NameError: name 'Batting' is not defined

# How slicing in handled in SQl ALchemy 

[Stack Overflow.](http://stackoverflow.com/questions/12111925/how-can-i-limit-the-number-of-returned-results-to-only-the-1000-latest-entries-w)

`limitedQuery = q[:50]`

[Slice](http://docs.sqlalchemy.org/en/improve_toc/orm/query.html) can be seen here.

# How Blaze Slicing works

In [69]:
import numpy as np

In [71]:
array = np.array(range(2,24))

In [73]:
len(array[:5])

5

In [75]:
d_array = Data(array)

In [77]:
len(d_array[:5])

5

# Design Choices

1. Test directly with computation
2. Use the compute function to work. 

Try (2) first because it is more traditional. It might be worth looking at this in the future to see how that works.

# Sql compute test

In [82]:

metadata = sa.MetaData()

s = sa.Table('accounts', metadata,
             sa.Column('name', sa.String),
             sa.Column('amount', sa.Integer),
             sa.Column('id', sa.Integer, primary_key=True))

In [83]:
s

Table('accounts', MetaData(bind=None), Column('name', String(), table=<accounts>), Column('amount', Integer(), table=<accounts>), Column('id', Integer(), table=<accounts>, primary_key=True, nullable=False), schema=None)

In [88]:
from blaze.compute.sql import (compute, computefull, select, lower_column,
                               compute_up)
import re
def normalize(s):
    s = ' '.join(s.strip().split()).lower()
    s = re.sub(r'(alias)_?\d*', r'\1', s)
    return re.sub(r'__([A-Za-z_][A-Za-z_0-9]*)', r'\1', s)

def test_table():
    result = str(computefull(t, s))
    expected = """
    SELECT accounts.name, accounts.amount, accounts.id
    FROM accounts
    """.strip()

    assert normalize(result) == normalize(expected)
    print(result)
test_table()

SELECT accounts.name, accounts.amount, accounts.id 
FROM accounts


In [90]:
def test_selection():
    assert str(compute(t[t['amount'] == 0], s)) == \
        str(sa.select([s]).where(s.c.amount == 0))
    assert str(compute(t[t['amount'] > 150], s)) == \
        str(sa.select([s]).where(s.c.amount > 150))
    
test_selection()

In [95]:
print(compute(t[t['amount'] == 0], s))

SELECT accounts.name, accounts.amount, accounts.id 
FROM accounts 
WHERE accounts.amount = :amount_1


In [93]:
print(sa.select([s]).where(s.c.amount == 0))

SELECT accounts.name, accounts.amount, accounts.id 
FROM accounts 
WHERE accounts.amount = :amount_1


In [81]:
s = sa.Table('accounts', metadata,
             sa.Column('name', sa.String),
             sa.Column('amount', sa.Integer),
             sa.Column('id', sa.Integer, primary_key=True))

NameError: name 'metadata' is not defined

In [195]:
import sqlalchemy as sa
def data():
    # make the engine
    engine = sa.create_engine('sqlite:///:memory:')
    metadata = sa.MetaData(engine)

    # name table
    name = sa.Table('name', metadata,
                    sa.Column('id', sa.Integer),
                    sa.Column('name', sa.String),
                    )
    name.create()

    # city table
    city = sa.Table('city', metadata,
                    sa.Column('id', sa.Integer),
                    sa.Column('city', sa.String),
                    sa.Column('country', sa.String),
                    )
    city.create()

    s = symbol('s', discover(engine))
    return {'engine': engine, 'metadata': metadata, 'name': name, 'city': city,
            's': s}

In [196]:
data = data()

In [103]:
type(data)

dict

In [110]:
type(data['s'])

blaze.expr.expressions.Symbol

## Making the SQL Dataset

Comes from line 1034 of test SQL

In [190]:
from blaze import join, by, into


engine = sa.create_engine('sqlite:///:memory:')

df_aaa = pd.DataFrame({'x': [1, 2, 3, 2, 3],
                    'y': [2, 1, 2, 3, 1],
                    'z': [3, 3, 3, 1, 2]})
df_bbb = pd.DataFrame({'w': [1, 2, 3, 2, 3],
                    'x': [2, 1, 2, 3, 1],
                    'y': [3, 3, 3, 1, 2]})

df_aaa.to_sql('aaa', engine)
df_bbb.to_sql('bbb', engine)

metadata = sa.MetaData(engine)
metadata.reflect()

sql_aaa = metadata.tables['aaa']
sql_bbb = metadata.tables['bbb']

L = symbol('aaa', discover(df_aaa))
R = symbol('bbb', discover(df_bbb))

expr = join(by(L.x, y_total=L.y.sum()),
                R)

a = compute(expr, {L: df_aaa, R: df_bbb})

b = compute(expr, {L: sql_aaa, R: sql_bbb})

### Now for the testing, we have that

In [185]:
into(pd.DataFrame,a)

0  1  2  3
0  1  2  2  3
1  1  2  3  2
2  2  4  1  3
3  2  4  3  3
4  3  3  2  1

In [187]:
for row in into(pd.DataFrame,b):
    print(row)

0
1
2
3


In [189]:
len(into(pd.DataFrame,b)) == len(into(pd.DataFrame, a))

True

In [186]:
into(pd.DataFrame,b).isin(i for i in into(pd.DataFrame,a))

0      1     2     3
0  True  False  True  True
1  True   True  True  True
2  True  False  True  True
3  True   True  True  True
4  True   True  True  True

# How we will test  

Numpy Test slicing works like this:

In [201]:
ax = np.arange(30, dtype='f4').reshape((5, 3, 2))

a = symbol('a', discover(ax))


inds = [0, slice(2), slice(1, 3), slice(None, None, 2), [1, 2, 3],
        (0, 1), (0, slice(1, 3)), (slice(0, 3), slice(3, 1, -1)),
        (0, [1, 2])]
for s in inds:
    print(compute(a[s], ax))


[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]]
[[[  0.   1.]
  [  2.   3.]
  [  4.   5.]]

 [[  6.   7.]
  [  8.   9.]
  [ 10.  11.]]]
[[[  6.   7.]
  [  8.   9.]
  [ 10.  11.]]

 [[ 12.  13.]
  [ 14.  15.]
  [ 16.  17.]]]
[[[  0.   1.]
  [  2.   3.]
  [  4.   5.]]

 [[ 12.  13.]
  [ 14.  15.]
  [ 16.  17.]]

 [[ 24.  25.]
  [ 26.  27.]
  [ 28.  29.]]]
[[[  6.   7.]
  [  8.   9.]
  [ 10.  11.]]

 [[ 12.  13.]
  [ 14.  15.]
  [ 16.  17.]]

 [[ 18.  19.]
  [ 20.  21.]
  [ 22.  23.]]]
[ 2.  3.]
[[ 2.  3.]
 [ 4.  5.]]
[[[  4.   5.]]

 [[ 10.  11.]]

 [[ 16.  17.]]]
[[ 2.  3.]
 [ 4.  5.]]


In [202]:
a[:5]

a[:5]

# Modifying the test 

In [232]:
def test_join_on_same_table():
    metadata = sa.MetaData()
    T = sa.Table('tab', metadata,
                 sa.Column('a', sa.Integer),
                 sa.Column('b', sa.Integer),
                 )

    t = symbol('tab', discover(T))
    expr = join(t, t, 'a')

    result = compute(expr, {t: T})

    assert normalize(str(result)) == normalize("""
    SELECT tab_left.a, tab_left.b, tab_right.b
    FROM tab AS tab_left JOIN tab AS tab_right
    ON tab_left.a = tab_right.a
    """)

In [233]:
test_join_on_same_table()

In [237]:
metadata = sa.MetaData()
T = sa.Table('tab', metadata,
                 sa.Column('a', sa.Integer),
                 sa.Column('b', sa.Integer),
                 )

In [314]:
t = symbol('t', discover(T))

In [239]:
expr = join(t, t, 'a')

In [256]:
limit = 50
offset = 50
expected = normalize("""
SELECT * FROM accounts LIMIT {0} OFFSET {1}
""").format(limit, offset)

ERROR: An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line string', (1, 0))



IndexError: tuple index out of range

In [255]:
expected

'select * from accounts limit 50 offset 50'

In [ ]:
def test_distinct_multiple_columns():
    assert normalize(str(compute(t.distinct(), s))) == normalize("""
    SELECT DISTINCT accounts.name, accounts.amount, accounts.id
    FROM accounts""")

# The Slicing Test

## Testing with Ipython

In [307]:
import sys
sys.path.append('/Users/Will/Devel/git/blaze/blaze/__init__.py')
sys.path.reverse()
import blaze

In [306]:
sys.path = ['/Users/Will/Devel/git/blaze/blaze/__init__.py']

In [ ]:
sys.path.reverse()
import blaze
assert blaze.__file__ ==  '/Users/Will/Devel/git/blaze/blaze/__init__.py'

from blaze import compute, symbol, discover
from blaze.compute.tests.test_sql_compute import normalize
import sqlalchemy as sa
import re
from blaze.compute.tests.test_sql_compute import test_slice

In [317]:
metadata = sa.MetaData()
s = sa.Table('accounts', metadata,
             sa.Column('name', sa.String),
             sa.Column('amount', sa.Integer),
             sa.Column('id', sa.Integer, primary_key=True))
t = symbol('t', discover(s))

def test_distinct_multiple_columns():
    assert normalize(str(compute(t.distinct(), s))) == normalize("""
    SELECT DISTINCT accounts.name, accounts.amount, accounts.id
    FROM accounts""")


def test_slicing(limit, offset):
    
    assert normalize(str(compute(t[50:100], s))) == normalize("""
    SELECT accounts.name, accounts.amount, accounts.id
    FROM accounts LIMIT {0} OFFSET {1}""").format(limit, offset)
    
def normalize(s):
    s = ' '.join(s.strip().split()).lower()
    s = re.sub(r'(alias)_?\d*', r'\1', s)
    return re.sub(r'__([A-Za-z_][A-Za-z_0-9]*)', r'\1', s)

test_distinct_multiple_columns()
#test_slice()
print(compute(t[50:100], s))

NotImplementedError: Don't know how to compute:
expr: tab[50:100]
data: {tab: Table('accounts', MetaData(bind=None), Column('name', String(), table=<accounts>), Column('amount', Integer(), table=<accounts>), Column('id', Integer(), table=<accounts>, primary_key=True, nullable=False), schema=None)}

In [295]:
sys.path

['',
 '/Users/Will/anaconda/envs/py34/lib/python34.zip',
 '/Users/Will/anaconda/envs/py34/lib/python3.4',
 '/Users/Will/anaconda/envs/py34/lib/python3.4/plat-darwin',
 '/Users/Will/anaconda/envs/py34/lib/python3.4/lib-dynload',
 '/Users/Will/anaconda/envs/py34/lib/python3.4/site-packages/setuptools-15.1-py3.4.egg',
 '/Users/Will/anaconda/envs/py34/lib/python3.4/site-packages',
 '/Users/Will/anaconda/envs/py34/lib/python3.4/site-packages/Sphinx-1.2.3-py3.4.egg',
 '/Users/Will/anaconda/envs/py34/lib/python3.4/site-packages/aeosa',
 '/Users/Will/anaconda/envs/py34/lib/python3.4/site-packages/IPython/extensions',
 '/Users/Will/.ipython']

In [265]:
expr = t[50:100]

In [274]:
expr.index

(slice(50, 100, None),)

In [273]:
type(expr.index[0])

slice

In [ ]:
@dispatch(Head, Select)
def compute_up(t, s, **kwargs):
    if s._limit is not None and s._limit <= t.n:
        return s
    return s.limit(t.n)


@dispatch(Head, ClauseElement)
def compute_up(t, s, **kwargs):
    return select(s).limit(t.n)


In [ ]:
def compute_up(expr, data, **kwargs):
    index = expr.index
    if isinstance(index, slice):
        start = index.start
        if start < 0:
            raise ValueError('start value of slice cannot be negative')
        stop = index.stop
        if stop < 0:
            raise ValueError('stop value of slice cannot be negative')
        if index.step is not None:
            raise ValueError('step parameter in slice objects not supported')
    elif isinstance(index, (np.integer, numbers.Integral, tuple())):
        if index < 0:
            raise ValueError('integer slice cannot be negative for the SQL backend')
        start = index
        stop = start + 1
    else:
        raise TypeError('type %r not supported for slicing' % type(index).__name__)
    return data.offset(start).limit(stop)

## Head

This one is the closest to what I am trying to do. Note that :param1 can just be anything.

In [ ]:
@dispatch(Head, Select)
def compute_up(t, s, **kwargs):
    if s._limit is not None and s._limit <= t.n:
        return s
    return s.limit(t.n)


@dispatch(Head, ClauseElement)
def compute_up(t, s, **kwargs):
    return select(s).limit(t.n)

`t` is the head expression and `s` is the select expression. `n`

## head Test

In [ ]:
assert normalize(str(compute(t[50:100], s))) == normalize("""
    SELECT accounts.name, accounts.amount, accounts.id
    FROM accounts LIMIT {0} OFFSET {1}""").format(limit, offset)

In [288]:
def test_head():
    assert str(compute(t.head(2), s)) == str(select(s).limit(2))

# Select Vs Selectable Vs `ClauseElement`

Selectable comes from SQLAlchemy is extends `ClauseElement`. Select is a representaiton of the SELECT operation in SQL. 

# Table Column and MetaData objects

`metadata = MetaData()` is a container that keeps together many different features of a database. We then represent a table via: 


```python
user = Table('user', metadata,
    Column('user_id', Integer, primary_key = True),
    Column('user_name', String(16), nullable = False),
    Column('email_address', String(60)),
    Column('password', String(20), nullable = False)
)```



# Moves forward
1. Learn better how the Slice thing works
2. Look at isnull implementation again
3. why data.offset works

# SQLALchemy Tutotiral
SqlAlchemy handles logging via `echo`.

 ```
  engine = create_engine('sqlite:///:memory:', echo=True)
```

The first thing to do with an engine is either to connect or ot execute. 

Interestingly, flask uses db.create_all() to make a table where db is a Flask.SqlAlchemy object. SqlAlchemy itself rathers that you do this `metadata.create_all(engine) `. 

# Progress

`type(t[:50])
Out[5]: blaze.expr.expressions.Slice`

So the type of the slice is good. b

## replace_slices in utils.py 

# Final testing

In [313]:
from multipledispatch import dispatch
from blaze.expr import Slice
from sqlalchemy.sql.elements import ClauseElement

@dispatch(Slice, ClauseElement)
def compute_up(t, s, **kwargs):
    index = t.index[0]
    if isinstance(index, slice):
        start = index.start
        if start < 0:
            raise ValueError('start value of slice cannot be negative')
        stop = index.stop
        if stop < 0:
            raise ValueError('stop value of slice cannot be negative')
        if index.step is not None:
            raise ValueError('step parameter in slice objects not supported')
    elif isinstance(index, (np.integer, numbers.Integral)):
        if index < 0:
            raise ValueError('integer slice cannot be negative for the SQL backend')
        start = index
        stop = start + 1
    else:
        raise TypeError('type %r not supported for slicing' % type(index).__name__)
    return select(s).limit(start).offset(stop)
    # return s.limit(start).offset(stop)
    
slce = compute_up(t[50:100], s)

NotImplementedError: Could not find signature for compute_up: <Slice, slice>

## Why does the test fail

In [286]:
    inds = [0, slice(2), slice(1, 3), [1, 2, 3],
            (0, 1), (0, slice(1, 3)), (slice(0, 3))]
    
    for s in inds:
        assert (compute(a[s], ax) == ax[s]).all()

# Questions 

There is a `compute_up` method that has `@dispatch(Head, Select)` rather than `ClauseElement` or `Selectable`. When would this be called? Do I need to worry about this in slicing. 

## My Questions

- Should I have more robust tests like in NumPy?
- Maybe use hypothesis here. 


# New Testing 

This is what the Pandas testing looks like. The same should be done there. 

In [ ]:
def test_slice():
    assert (compute(t[0], df) == df.iloc[0]).all()
    assert (compute(t[2], df) == df.iloc[2]).all()
    assert (compute(t[:2], df) == df.iloc[:2]).all().all()
    assert (compute(t[1:3], df) == df.iloc[1:3]).all().all()
    assert (compute(t[1::2], df) == df.iloc[1::2]).all().all()

# How the Slicing Function works 

1. 

In [7]:
from blaze.expr.utils import _slice

In [8]:
class hashable_list(tuple):
    def __str__(self):
        return str(list(self))

def replace_slices(index):
    """
    Takes input from Slice expression and returns the proper type
    for further processing.

    Examples
    -------
    

    """
    if isinstance(index, hashable_list):
        return list(index)
    elif isinstance(index, _slice):
        return index.as_slice()
    elif isinstance(index, tuple):
        return tuple(map(replace_slices, index))
    return index

In [13]:
type(replace_slices((2,5)))

tuple

In [18]:
type(replace_slices(_slice(1,5, None)))

slice

In [17]:
replace_slices(_slice(1,5, None))

slice(1, 5, None)

In [19]:
type(replace_slices(_slice(1,5, None))) is slice

True